networks:
  vllm_openweb_ui_net:

services:
  vllm_openai:
    image: vllm/vllm-openai:v0.8.5

    command:
      - "--config-format=auto" # нужно чтобы следующий аргумент распарсился
      - "--config"
      - "/config/vllm.yaml"
    ports:
      - "8953:8000"
    volumes:
      - ./models_cache:/root/.cache/huggingface/hub
      - ./vllm_args.yaml:/config/vllm.yaml
      - ./compile_cache:/root/.cache/vllm

    shm_size: "30g"
    # cpuset: "0-3"
    restart: none
    environment:
      PYTORCH_CUDA_ALLOC_CONF: expandable_segments:True #,backend:cudaMallocAsync #,max_split_size_mb:512
      CUDA_DEVICE_ORDER: FASTEST_FIRST
      # TF_FORCE_GPU_ALLOW_GROWTH: True
      # TRANSFORMERS_OFFLINE: 1
      VLLM_USE_V1: 1
    networks:
      - vllm_openweb_ui_net

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 60s
      retries: 3
      start_period: 400s

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["1"]
              # count: all # подключить вообще всё, на проде не рекомендуется
