networks:
  vllm_openweb_ui_net:

services:
  vllm_openai:
    # image: vllm/vllm-openai:v0.8.5.post1
    build:
      context: .
      dockerfile: LmCache.Dockerfile

    command:
      - "--config-format=auto" # нужно чтобы следующий аргумент распарсился
      - "--config"
      - "/config/vllm.yaml"
    ports:
      - "8953:8000"
    volumes:
      - ./models_cache:/root/.cache/huggingface/hub
      - ./vllm_args.yaml:/config/vllm.yaml
      - ./compile_cache:/root/.cache/vllm

    shm_size: "30g"
    restart: none
    environment:
      PYTORCH_CUDA_ALLOC_CONF: expandable_segments:True #,backend:cudaMallocAsync #,max_split_size_mb:512
      CUDA_DEVICE_ORDER: PCI_BUS_ID # FASTEST_FIRST
      LMCACHE_USE_EXPERIMENTAL: True
      LMCACHE_CHUNK_SIZE: 256
      LMCACHE_LOCAL_CPU: True
      LMCACHE_MAX_LOCAL_CPU_SIZE: 5.0
      # TF_FORCE_GPU_ALLOW_GROWTH: True
      # TRANSFORMERS_OFFLINE: 1
      # VLLM_USE_V1: 0
      # VLLM_PP_LAYER_PARTITION: "9,27"
      # OMP_NUM_THREADS: 5
    networks:
      - vllm_openweb_ui_net

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 60s
      retries: 3
      start_period: 400s

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["1"]
              # count: all # подключить вообще всё, на проде не рекомендуется
