services:
  prometheus:
    image: prom/prometheus:latest
    extra_hosts:
      - "host.docker.internal:host-gateway" # allow a direct connection from container to the local machine
    ports:
      - "9590:9090" # the default port used by Prometheus
    volumes:
      - ${PWD}/prometheus.yaml:/etc/prometheus/prometheus.yml # mount Prometheus config file
    networks:
      - vllm_openweb_ui_net

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "8947:3000" # the default port used by Grafana
    volumes:
      - grafana_lib:/var/lib/grafana
      - grafana_prom:/etc/grafana/provisioning/
    networks:
      - vllm_openweb_ui_net

volumes:
  grafana_lib:
  grafana_prom:
