# prometheus.yaml
global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: vllm
    static_configs:
      - targets:
          # - "host.docker.internal:8000"
          - "vllm_openai:8000"
  # - job_name: sglang
  #   scheme: http
  #   bearer_token: NYXV2sS3PLDYLbC
  #   static_configs:
  #     - targets:
  #         - "host.docker.internal:8765"
